# Introduction to the Forest Fire Model

## What is the Forest Fire Model?

Picture a grid like a checkerboard, where each square (or "cell") can be empty, have a tree, or be on fire. The **Forest Fire Model (FFM)** is a computer simulation that acts like a game to show how fire spreads through a forest and how trees grow back over time. It’s a type of *cellular automaton*, which is a fancy way of saying a model where simple rules for each square create complex patterns across the whole grid. Scientists use this model to study how small, local changes—like a single tree catching fire—can lead to big, system-wide effects, like massive wildfires.


The FFM was first developed by researchers like Bak, Chen, and Tang, and later improved by Drossel and Schwabl, to explore how simple rules can create complicated behaviors in nature. For example, it helps scientists understand how fires of different sizes happen or how dense a forest might become over time. The model mimics three key processes: fire spreading from tree to tree, new trees growing, and random events like lightning starting fires.

## Forest Fire Model vs. Wildfire Modeling

The term "Forest Fire Model" can be confusing because it’s used in two different ways. In physics and math, the FFM refers to this simple, abstract grid-based model we’re talking about. It’s designed to study ideas, like how systems naturally organize themselves into a "critical" state where fires of all sizes can happen (a concept called **self-organized criticality**). But in real-world forestry and fire management, "forest fire models" or "wildfire models" (like FARSITE or BehavePlus) are much more detailed. These practical models include things like specific types of plants, hills and valleys, wind, humidity, and fire behavior to predict real wildfires accurately.

So, while the simple FFM is like a basic sketch to understand core ideas, real-world wildfire models are like detailed blueprints for actual forests. In the Capstone project, you should use the basic Forest Fire Model as a starting point and add elements that lead to more physically realistic scenarios.

## How Does the FFM Work?

Unlike some math models that use continuous equations (like those for population growth), the FFM works in a grid with discrete steps. Each square’s state—empty, tree, or fire—changes based on its own condition and what’s happening in the squares next to it. For example, a tree might catch fire if a neighboring square is burning, or an empty square might grow a new tree over time. These updates happen in time steps, like turns in a board game.

The FFM is a great way to explore how complex patterns, like unpredictable fire sizes, can come from simple rules. It’s especially useful for studying self-organized criticality, where a system naturally settles into a state where both small and huge events (like fires) can happen at any time.

## Key Components and Rules

The model typically operates on a 2D lattice (grid). Each cell in the grid can exist in one of three states:
* **Empty (or Ash):** Represents bare ground where a tree could potentially grow.
* **Tree (or Fuel):** Represents a living tree or flammable vegetation.
* **Burning:** Represents a tree that is currently on fire.

The system evolves in discrete time steps. During each step, the state of every cell is updated simultaneously (or sequentially in some implementations) based on the following rules (using the Drossel-Schwabl variant as a common example):

1.  **Burning Decay:** A cell that is currently *Burning* becomes *Empty* in the next time step (the fire consumes the fuel).
2.  **Fire Spread:** A *Tree* cell becomes *Burning* in the next time step if at least one of its immediate neighbors (e.g., the four von Neumann neighbors: North, South, East, West) is currently *Burning*.
3.  **Lightning Strike (Spontaneous Ignition):** A *Tree* cell that did not catch fire from a neighbor becomes *Burning* with a small probability, $f$. This represents random ignition events like lightning.
4.  **Tree Growth:** An *Empty* cell becomes a *Tree* with a certain probability, $p$, in the next time step. This represents regrowth.

The parameters $p$ (growth probability) and $f$ (lightning probability) control the overall dynamics of the system. Typically, $f$ is much smaller than $p$ ($f \ll p$).

## Why is the Forest Fire Model Important?

Even though the Forest Fire Model (FFM) is simple, it creates fascinating and complex patterns, making it a powerful tool for understanding nature and science. Here’s why it matters:

* **Showing Self-Organized Criticality (SOC):** The FFM is a classic example of a system that naturally settles into a "critical" state, where fires of all sizes can happen. Small fires are common, but huge, landscape-changing fires are possible too. This follows a pattern called a power-law, meaning the size of fires varies widely, all from simple rules without any outside tweaking.
* **Creating Complex Patterns:** The model shows how simple actions, like a fire spreading to a nearby tree, can lead to big, intricate results. For example, it can create jagged fire edges, changing forest densities, or patterns that look like they follow a mathematical recipe, even though they come from basic grid rules.
* **Understanding Ecosystems:** The FFM gives a simple way to think about real-world forests, like how fires shape landscapes, break up habitats, or help ecosystems change over time. It’s like a starting point for studying nature’s cycles.
* **Inspiring Real Wildfire Tools:** While the FFM is a basic sketch, its ideas—using a grid, tracking changes, and including random events like lightning—helped spark the creation of advanced wildfire models. These detailed tools predict real fires, assess risks, and guide forest management today.
* **Exploring Physics Ideas:** The model helps scientists study big concepts, like how systems shift from one state to another (think of a sparse forest with small fires versus a dense one with huge fires). It connects to ideas in physics about how things spread, like water soaking through a sponge.
* **Teaching Computer Simulations:** The FFM is a great example for learning how to build and study computer models. It’s like a fun, simple game that teaches students about cellular automata (grid-based simulations) and how to analyze complex systems.

By studying the FFM, we see how unpredictable events, like massive wildfires, might be a natural part of systems that are on the edge of big changes. This idea is useful even when looking at more detailed wildfire models.

## Algorithmic Representation

The simulation of the Forest Fire Model typically proceeds as follows:

1.  **Initialization:** Create a grid (e.g., an $L \times L$ matrix) and initialize the state of each cell, often starting with an empty grid or a random distribution of states.
2.  **Time Evolution Loop:** Repeat for a desired number of time steps:
    * Create a new grid (e.g., `next_grid`) of the same size to store the states for the next time step, typically initialized as a copy of the current grid or empty.
    * **Iterate through each cell $(i, j)$ of the current grid:**
        * **Check Burning Cells:** If `current_grid[i, j]` is *Burning*, set `next_grid[i, j]` to *Empty*.
        * **Check Tree Cells:** If `current_grid[i, j]` is *Tree*:
            * Check its neighbors in `current_grid`. If any neighbor is *Burning*, set `next_grid[i, j]` to *Burning*.
            * If no neighbor is burning, check for lightning: generate a random number $r \in [0, 1]$. If $r < f$, set `next_grid[i, j]` to *Burning*.
            * If no neighbor is burning and no lightning strike occurs, the cell remains a *Tree* (i.e., `next_grid[i, j]` stays *Tree*).
        * **Check Empty Cells:** If `current_grid[i, j]` is *Empty*:
            * Check for growth: generate a random number $r \in [0, 1]$. If $r < p$, set `next_grid[i, j]` to *Tree*.
            * Otherwise, it remains *Empty* (`next_grid[i, j]` stays *Empty*).
    * **Update Grid:** Replace the `current_grid` with the `next_grid` for the next iteration.
    * *(Optional)* Record data: Measure the size of active fires, density of trees, etc. Visualize the grid state.

> **Note:** Careful implementation is needed regarding the order of updates, especially whether fire spread, lightning, and growth are evaluated based on the grid state at the beginning of the time step or potentially updated sequentially within the step. The simultaneous update described above (using a `next_grid`) is common. Boundary conditions (e.g., periodic or fixed) also need to be defined.

## Python Implementation Example

### Model Parameters and Setup
* **Grid States:** $0$ = Empty, $1$ = Tree, $2$ = Burning
* $p$: Probability of tree growth (Empty $\to$ Tree)
* $f$: Probability of spontaneous ignition (Tree $\to$ Burning)
* `L`: Grid dimension ($L \times L$)
* `num_steps`: Number of simulation steps

Run the cell below to import the required Python libraries and define the global simulation constants.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import matplotlib.animation as animation
from IPython.display import HTML


# ==========================================
# 1. Simulation Parameters & Constants
# ==========================================
GRID_SIZE = 100                     # Dimensions of the forest (NxN)
TOTAL_STEPS = 200                   # Total duration of the simulation
PROB_IGNITION = 0.0001  # Chance of lightning (f)
PROB_GROWTH = 0.02             # Chance of a new tree (p)

# State Constants
STATE_EMPTY = 0   #  ⬛️ Ground     
STATE_TREE = 1    #  🟢 Tree  
STATE_BURNING = 2 #. 🔥 Fire

# Define standard colors for our states: [Brown/Grey, Green, Orange-Red]
color_ground = [76/255,  66/255,  70/255]  
color_trees  = [118/255, 176/255,  65/255] 
color_fire   = [228/255,  87/255,  46/255] 

### Understanding the Parameters

The two most important parameters controlling the simulation's behavior are `PROB_GROWTH` ($p$) and `PROB_IGNITION` ($f$):

* **`PROB_GROWTH = 0.02`** means that in each time step, any empty cell has a 2% chance of sprouting a new tree. This represents natural forest regeneration — seeds germinating, saplings taking root.
* **`PROB_IGNITION = 0.0001`** means a tree cell has a 0.01% chance per step of catching fire spontaneously (e.g. from lightning). This is intentionally very small, so that the forest has time to grow and become dense before a fire sweeps through it.

The ratio $p/f = 200$ is the critical quantity. When this ratio is large, the forest grows much faster than it burns, leading to a landscape where large connected clusters of trees can form — and when a fire does ignite, it can spread far. Try experimenting with different values to see how the dynamics change!

> **Tip:** Increasing `PROB_IGNITION` closer to `PROB_GROWTH` will produce a sparser forest with mostly small fires. Decreasing it further will allow the forest to grow very dense, producing infrequent but catastrophic fires.

### Helper Functions

The `is_neighbor_burning` function checks the 8 Moore neighbors of the cell for fire. The `calculateNextState` function determines the next state of a cell based on its current state, whether a neighbor is burning, and the growth/ignition probabilities.

The cell below defines `is_neighbor_burning`, which inspects all eight surrounding cells (Moore neighborhood) and returns `True` as soon as it finds a burning cell.

In [2]:
def is_neighbor_burning(row, col, forest_grid):
    # Dynamically get the size from the grid itself
    current_grid_size = len(forest_grid) 
    
    for row_offset in [-1, 0, 1]:
        for col_offset in [-1, 0, 1]:
            if row_offset == 0 and col_offset == 0:
                continue
            
            neighbor_row = row + row_offset
            neighbor_col = col + col_offset
            
            # Use the dynamic size here instead of the global GRID_SIZE
            is_within_bounds = (0 <= neighbor_row < current_grid_size) and (0 <= neighbor_col < current_grid_size)
            
            if is_within_bounds:
                if forest_grid[neighbor_row, neighbor_col] == STATE_BURNING:
                    return True
    return False

#### Moore vs. Von Neumann Neighborhoods

Notice that the nested loop iterates over `row_offset` and `col_offset` in `[-1, 0, 1]`, covering all 8 surrounding cells. This is called the **Moore neighborhood**. It is one of two common choices:

| Neighborhood | Cells Checked | Shape |
|---|---|---|
| **Von Neumann** | 4 (N, S, E, W only) | Plus / Cross |
| **Moore** | 8 (includes diagonals) | Square |

Using the Moore neighborhood means fire can spread diagonally, which tends to produce more realistic-looking, rounded fire perimeters. The Von Neumann neighborhood would produce diamond-shaped fire fronts.

The `if row_offset == 0 and col_offset == 0: continue` line simply skips the cell itself (we only want to look at *neighbors*, not the cell being evaluated).

### Testing the Neighborhood Function

To understand how the `is_neighbor_burning` function works, it helps to run a small, controlled test. The function uses a **Moore neighborhood**, meaning it checks all eight cells immediately surrounding a target cell (up, down, left, right, and the four diagonals) to see if any of them contain the `STATE_BURNING` state.

In the code block below, we define a tiny 4x4 grid to simulate a micro-forest:
* `0` represents an empty space.
* `1` represents a tree.
* `2` represents a burning tree.

We placed a single burning tree near the top left, at coordinates `row 1, col 1`. 

We will test two different cells to see if the function correctly detects the fire:
1. **Test A (Close proximity):** We check the tree at `(0, 1)`. Because it is directly above the fire, the function should iterate through its neighbors, detect the `2` at `(1, 1)`, and return `True`.
2. **Test B (Far away & Boundary check):** We check the tree at the bottom-right corner, `(3, 3)`. The fire is too far away, so it should return `False`. This also perfectly tests our grid boundary logic (`0 <= nr < L`), ensuring the program doesn't crash when it tries to check for neighbors outside the edges of our 4x4 map.

We now build a small 5 × 5 test grid by hand so we can verify `is_neighbor_burning` with a known layout before running the full simulation.

In [3]:
# --- 5x5 Matrix with ~50% Trees ---
test_grid = np.array([   #   col 0  1  2  3  4   
    [1, 0, 1, 0, 1],     # row 0 🟢 ⬛️ 🟢 ⬛️ 🟢 
    [0, 1, 2, 1, 0],     #     1 ⬛️ 🟢 🔥 🟢 ⬛️ 
    [1, 1, 1, 0, 1],     #     2 🟢 🟢 🟢 ⬛️ 🟢 
    [0, 0, 1, 1, 0],     #     3 ⬛️ ⬛️ 🟢 🟢 ⬛️ 
    [1, 0, 0, 0, 1]      #     4 🟢 ⬛️ ⬛️ ⬛️ 🟢 
])

row, colum = 1, 1
result = is_neighbor_burning(row, colum, test_grid)
print(f"Is there a fire near the tree at ({row}, {colum})? {result}")

Is there a fire near the tree at (1, 1)? True


The cell below defines `calculate_next_state`, which encodes the four transition rules of the Drossel–Schwabl model for a single cell.

In [4]:

def calculate_next_state(current_state, is_fire_nearby):
    """Determines what happens to a specific cell in the next time step."""
    if current_state == STATE_EMPTY:
        # An empty spot has a small chance to grow a new tree
        if np.random.rand() < PROB_GROWTH:
            return STATE_TREE
        else:
            return STATE_EMPTY

    elif current_state == STATE_TREE:   
        # A tree catches fire if a neighbor is burning OR if spontaneous ignition (lightning) occurs
        random_ignition_occurred = np.random.rand() < PROB_IGNITION
        
        if is_fire_nearby or random_ignition_occurred:
            return STATE_BURNING
        else:
            return STATE_TREE
            
    elif current_state == STATE_BURNING: 
        # A burning tree turns into ashes (empty space) in the next step
        return STATE_EMPTY
        
    else: 
        return current_state

### Testing `calculate_next_state`

Now that both helper functions are defined, let's verify that `calculate_next_state` correctly implements all the rules of the model. The five test cases below cover every possible situation a cell can face:

| # | Cell State | Fire Nearby? | Expected Next State | Rule Applied |
|---|---|---|---|---|
| 1 | Tree 🟢 | Yes 🔥 | Burning 🔥 | Fire spreads to adjacent tree |
| 2 | Tree 🟢 | No | Tree 🟢 (most likely) | No spread; lightning very rare |
| 3 | Burning 🔥 | — | Empty ⬛️ | Fire consumes itself in one step |
| 4 | Empty ⬛️ | No | Empty ⬛️ (most likely) | Regrowth is slow |
| 5 | Empty ⬛️ | Yes 🔥 | Empty ⬛️ | Empty ground cannot burn |

Case 5 is particularly important: it confirms that fire only spreads to *trees*, not to empty ground. This is what makes connected clusters of trees so influential — gaps in the forest act as natural firebreaks.

Run each of the five test cells below in order to check that every transition rule is implemented correctly.

In [5]:
# 1. Situation: Tree 🟢, Fire is nearby 🔥
result = calculate_next_state(STATE_TREE, is_fire_nearby=True)
print(f"Situation 1: Tree near fire should be {STATE_BURNING} (🔥). The result is: {result}")


Situation 1: Tree near fire should be 2 (🔥). The result is: 2


**Test 2 of 5 — Tree with no fire nearby.** Because `PROB_IGNITION` is very small, the tree will almost certainly remain a tree, but on rare runs you may see it ignite from simulated lightning.

In [6]:

# 2. Situation: Tree 🟢, No fire nearby (Checking for random lightning ⚡️)
result = calculate_next_state(STATE_TREE, is_fire_nearby=False)
print(f"Situation 2: Tree with no fire nearby is likely {STATE_TREE} (🟢). The result is: {result}")

Situation 2: Tree with no fire nearby is likely 1 (🟢). The result is: 1


**Test 3 of 5 — Burning tree.** A cell that is currently on fire always becomes empty in the very next time step.

In [7]:
# 3. Situation: Burning Tree 🔥, Next Step
result = calculate_next_state(STATE_BURNING, is_fire_nearby=False)
print(f"Situation 3: Burning tree should become {STATE_EMPTY} (⬛️). The result is: {result}")

Situation 3: Burning tree should become 0 (⬛️). The result is: 0


**Test 4 of 5 — Empty ground, no fire nearby.** With `PROB_GROWTH = 0.02` the cell has only a 2% chance of becoming a tree; it will most likely stay empty.

In [8]:
# 4. Situation: Empty Ground ⬛️, (Checking for random growth 🌱)
result = calculate_next_state(STATE_EMPTY, is_fire_nearby=False)
print(f"Situation 4: Empty ground is likely {STATE_EMPTY} (⬛️). The result is: {result}")

Situation 4: Empty ground is likely 0 (⬛️). The result is: 0


**Test 5 of 5 — Empty ground adjacent to fire.** Empty cells cannot catch fire, so the result must always be `STATE_EMPTY` regardless of nearby burning.

In [9]:
# 5. Situation: Empty Ground ⬛️, Fire is nearby 🔥
result = calculate_next_state(STATE_EMPTY, is_fire_nearby=True)
print(f"Situation 5: Empty ground near fire should stay {STATE_EMPTY} (⬛️). The result is: {result}")


Situation 5: Empty ground near fire should stay 0 (⬛️). The result is: 0


With both helper functions verified, we can now define `advance_forest_one_step`, which applies the rules simultaneously to every cell in the grid and returns the next grid.

In [10]:
def advance_forest_one_step(current_grid):
    """Calculates the next state of the entire forest grid, independent of visuals."""
    grid_size = len(current_grid)
    future_grid = np.zeros((grid_size, grid_size), dtype=int) 
    
    for row in range(grid_size):
        for col in range(grid_size): 
            # 1. Check neighbors
            is_fire_nearby = is_neighbor_burning(row, col, current_grid)
            
            # 2. Get current state
            current_state = current_grid[row, col]
            
            # 3. Calculate and store next state
            future_grid[row, col] = calculate_next_state(current_state, is_fire_nearby)
            
    return future_grid

### Testing the Full Grid Update

The `advance_forest_one_step` function ties everything together: it loops over every cell in the grid, calls `is_neighbor_burning` and `calculate_next_state` for each one, and builds the *next* grid from scratch before replacing the current one. This simultaneous update is important — all cells are evaluated based on the grid state at the *start* of the step, so a fire that spreads to a new tree in this step cannot immediately spread further until the *next* step.

The three print statements below let us inspect this logic on our small `test_grid`:
1. **`print(test_grid)`** — shows the starting state.
2. **`print(advance_forest_one_step(test_grid))`** — shows the grid after one step.
3. **`print(advance_forest_one_step(test_grid) - test_grid)`** — shows *only the cells that changed* (non-zero values mark transitions). This difference grid is a handy debugging technique to spot unexpected behavior.

Let's inspect the test grid before and after one step to confirm the full update works as expected.

In [11]:
print("Initial test grid:")
print(test_grid)

Initial test grid:
[[1 0 1 0 1]
 [0 1 2 1 0]
 [1 1 1 0 1]
 [0 0 1 1 0]
 [1 0 0 0 1]]


Now print the grid after one step. Burning cells should have turned empty, neighbouring trees should have caught fire, and a few empty cells may have sprouted trees.

In [12]:
print("Grid after one step:")
print(advance_forest_one_step(test_grid))

Grid after one step:
[[1 0 2 0 1]
 [0 2 0 2 0]
 [1 2 2 0 1]
 [0 0 1 1 0]
 [1 0 0 0 1]]


Subtracting the original grid from the updated one highlights only the cells that changed state. Non-zero entries mark every transition that occurred in this single step.

In [13]:
print("Difference (changed cells only):")
print(advance_forest_one_step(test_grid)-test_grid)

Difference (changed cells only):
[[ 0  0  1  0  0]
 [ 0  1 -2  1  0]
 [ 0  1  1  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]


### Main Simulation Loop
The code initializes an empty grid, sets up the visualization, and then iterates through time steps. It calculates the next state of each cell based on the rules and visualizes the grid state at each step.

### Initialisation Strategy

The simulation starts with `forest_grid = np.zeros(...)`, meaning every cell begins as **Empty**. This is a *cold start*: watch the first few dozen frames as trees slowly colonise the bare landscape before the first fires appear.

An alternative is to initialise with a random mix of trees and empty cells (e.g. `np.random.choice([STATE_EMPTY, STATE_TREE], size=(GRID_SIZE, GRID_SIZE), p=[0.5, 0.5])`). This can reduce the initial transient, but the system will still evolve toward the same statistical steady state regardless of starting conditions — a hallmark of self-organised criticality.

The cell below initialises the forest grid, configures the colour map, and runs the full animation using the modular `advance_forest_one_step` helper.

In [14]:
# --- Initialization & Visualization Setup ---
forest_grid = np.zeros((GRID_SIZE, GRID_SIZE), dtype=int) 

# Create the figure and axes
fig, ax = plt.subplots(figsize=(6, 6))
forest_cmap = ListedColormap([color_ground, color_trees, color_fire])
image_display_handle = ax.imshow(forest_grid, cmap=forest_cmap, vmin=STATE_EMPTY, vmax=STATE_BURNING)
ax.axis('off')

# --- Animation Logic ---

def update_plot(frame_number):
    """This function only handles updating the visual frame for the animation."""
    global forest_grid 
    
    # 1. Advance the mathematical model by one step
    forest_grid = advance_forest_one_step(forest_grid)
    
    # 2. Update the visual plot with the new data
    image_display_handle.set_data(forest_grid)
    ax.set_title(f'Forest Fire Model - Step {frame_number} / {TOTAL_STEPS}')
    
    return [image_display_handle] 

# Prevent the static initial plot from showing up twice
plt.close() 

# Compile the animation
forest_animation = animation.FuncAnimation(
    fig, update_plot, frames=TOTAL_STEPS, interval=50, blit=True
)

# --- Display ---
HTML(forest_animation.to_jshtml())

## Example Scenario

Running the simulation typically reveals characteristic dynamics:
* **Initial Transient:** If starting from a dense forest, large fires might initially sweep through until a balance is reached. If starting empty, the forest density gradually increases.
* **Statistical Steady State:** After the transient phase, the system often reaches a fluctuating steady state. The overall density of trees fluctuates around an average value.
* **Fire Dynamics:** Fires are constantly ignited by lightning. Most remain small and quickly burn out. Occasionally, a fire finds a large, connected cluster of trees and spreads significantly, sometimes clearing large areas of the grid.
* **Self-Organized Criticality:** The key observation is that the distribution of the sizes of these fire clusters (e.g., measured by the number of cells burned in one event) often follows a **power law**, $P(s) \propto s^{-\tau}$, where $s$ is the size and $\tau$ is a characteristic exponent. This indicates scale-invariance: there's no typical fire size, and events of all magnitudes occur, driven purely by the internal dynamics. Large, "catastrophic" fires are rare but an intrinsic part of the system's behavior.
* **Visual Patterns:** Observers can see fires propagating, often leaving behind complex, sometimes fractal-like boundaries between burnt and unburnt areas. Patches of regrowth appear in the empty areas.

This behavior contrasts with systems that might have a single characteristic scale or predictable, periodic behavior. The FFM shows how simple local rules generate complex, scale-free dynamics.

## Literature

### General Introduction
The Forest Fire Model is widely discussed in physics and complexity science literature. Online resources and textbooks on cellular automata or complex systems often cover it.
* [Forest Fire Model (Wikipedia)](https://en.wikipedia.org/wiki/Forest-fire_model)
* [A Cellular Automata Based Forest-Fire Model](https://itp.uni-frankfurt.de/~gros/StudentProjects/Projects_2020/projekt_lars_dingeldein/)

*(Note: Ensure you include your `references/projects.bib` foundational and journal club papers in your reference manager if continuing your research.)*

## Conclusion
The abstract Forest Fire Model demonstrates how simple, local rules can generate complex, large-scale behavior characteristic of many natural systems. Its ability to exhibit self-organized criticality without fine-tuning parameters makes it a conceptual model for understanding phenomena ranging from literal wildfires to stock market crashes or disease epidemics. It demonstrates the importance of spatial structure, local interactions, and stochasticity in shaping system-level dynamics. While it is highly simplified compared to real ecosystems and current wildfire prediction tools, its core principles offer valuable insights into disturbance, resilience, and the emergence of complexity.

## Recommended Reading & Journal Club

### Foundational Papers

The Forest Fire Model as studied in this notebook traces directly to three landmark papers.
Reading them in order shows how the model evolved from a rough physical analogy into a rigorously analysed self-organised critical system.

**1. Bak, Chen & Tang (1990)**
*A forest-fire model and some thoughts on turbulence.*
Physics Letters A, 147(5–6), 297–300. [DOI](https://doi.org/10.1016/0375-9601(90)90451-S)
→ Introduced the original FFM as an analogy for $1/f$ noise and turbulence; first demonstration of power-law fire-size distributions.

**2. Chen, Bak & Jensen (1990)**
*A deterministic critical forest fire model.*
Physics Letters A, 149(4), 207–210. [DOI](https://doi.org/10.1016/0375-9601(90)90328-L)
→ Deterministic variant showing that SOC does not require stochasticity; useful counterpoint to the probabilistic version implemented here.

**3. Drossel & Schwabl (1992)**
*Self-organized critical forest-fire model.*
Physical Review Letters, 69(11), 1629–1632. [DOI](https://doi.org/10.1103/PhysRevLett.69.1629)
→ The canonical stochastic model ($p$, $f$ parameters) implemented in this notebook; proved true SOC in the limit $f/p \to 0$.

---

### Journal Club — Cellular Automata & Realistic Fire Spread

These papers extend the abstract FFM toward physically realistic wildfire simulation. Each adds one or two new ingredients — terrain, wind, fuel moisture, or machine-learned rules — on top of the basic CA framework you have just built.

**4. Alexandridis et al. (2008)**
*A cellular automata model for forest fire spread prediction: The case of the wildfire that swept through Spetses Island in 1990.*
Applied Mathematics and Computation, 204(1), 191–201. [DOI](https://doi.org/10.1016/j.amc.2008.06.046)
→ Incorporates vegetation type, slope, and wind into the CA rules; validated against a real historical fire event. A good entry point for adding physical realism.

**5. Freire & DaCamara (2019)**
*Using cellular automata to simulate wildfire propagation and to assist in fire management.*
Natural Hazards and Earth System Sciences, 19(1), 169–179. [DOI](https://doi.org/10.5194/nhess-19-169-2019)
→ Couples CA propagation with fire-management strategies such as firebreaks and suppression. Open-access.

**6. Rui et al. (2017)**
*Forest fire spread simulation algorithm based on cellular automata.*
Natural Hazards, 91(1), 309–319. [DOI](https://doi.org/10.1007/s11069-017-3127-5)
→ Introduces a probabilistic spread function that accounts for wind direction and speed explicitly.

**7. Mutthulakshmi et al. (2020)**
*Simulating forest fire spread and fire-fighting using cellular automata.*
Chinese Journal of Physics, 65, 642–650. [DOI](https://doi.org/10.1016/j.cjph.2020.04.001)
→ Models active fire-fighting agents inside the CA; links to epidemic and game-theoretic ideas.

**8. Zheng et al. (2017)**
*Forest fire spread simulating model using cellular automata with extreme learning machine.*
Ecological Modelling, 348, 33–43. [DOI](https://doi.org/10.1016/j.ecolmodel.2016.12.022)
→ Replaces hand-crafted transition rules with an ELM trained on real fire data — a bridge between classical CA and modern ML.

**9. Zhou et al. (2025)**
*Modeling the spread of forest fires through cellular automata by leveraging deep learning to derive transition rules.*
Ecological Informatics, 88, 103150. [DOI](https://doi.org/10.1016/j.ecoinf.2025.103150)
→ Uses deep learning to learn CA transition rules end-to-end from satellite imagery; the most recent entry in this list.

